name: deployment status test

on:
  workflow_dispatch:

  deployment:

jobs:
  # tests_from_workflow_dispatch:
  #   if: ${{ github.event.workflow_run == 'success' }} || ${{ github.event.workflow_run == 'failure' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Status
  #       env:
  #         VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
  #         TEST_VAR: true
  #       if: env.TEST_VAR == true
  #       run: echo TEST_VAR true

  # tests_from_production_deployment:
  #   if: ${{ github.event.deployment_status.state == 'success' }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Status
  #       env:
  #         VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
  #         TEST_VAR: false
  #       if: env.TEST_VAR == false
  #       run: echo TEST_VAR false
  common:
    if: ${{ github.event.deployment_status.state == 'success' }} && ${{ github.event.deployment_status.environment == 'Production' }}
    runs-on: ubuntu-latest
    steps:
      - name: state
        env:
          VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
        run: echo $VERCEL_DEPLOYMENT_STATUS

  # work:
  #   if: ${{ github.event.deployment_status.state == null }}
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: state
  #       env:
  #         VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event) }}
  #       run: echo $VERCEL_DEPLOYMENT_STATUS
