name: deployment status test

on:
  deployment_status

jobs:
  tests:
    steps:
      - name: Status
        if: {{ github.event.deployment_status }}
        run: echo "Status = {{ github.event.deployment_status }}"
        