name: deployment status test

on:
  deployment_status

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Status
        env:
          VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
        run: echo ${{ VERCEL_DEPLOYMENT_STATUS }}
        