name: deployment status test

on: [workflow_dispatch, deployment_status]

jobs:
  common:
    runs-on: ubuntu-latest
    steps:
      - name: common
        run: echo ${{ github.event.type }}

  tests_from_workflow_dispatch:
    if: ${{ github.event.action }} == 'workflow_dispatch'
    runs-on: ubuntu-latest
    steps:
      - name: Status
        env:
          VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
          TEST_VAR: true
        if: env.TEST_VAR == true
        run: echo TEST_VAR true

  tests_from_production_deployment:
    if: ${{ github.event.action }} == 'deployment_status'
    runs-on: ubuntu-latest
    steps:
      - name: Status
        env:
          VERCEL_DEPLOYMENT_STATUS: ${{ toJson(github.event.deployment_status) }}
          TEST_VAR: false
        if: env.TEST_VAR == false
        run: echo TEST_VAR false